import Head from 'next/head'
import { useEffect ,useState } from 'react'
import axios from "axios"
import dynamic from 'next/dynamic'
import { useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
const GetUsdcTokenBalance = dynamic(() => import('../components/getUsdcTokenBalance'))

// comment  componentleri dinamik import etmek  ucun lazimdi  render olunur sehifeye daxil olanda


const Home = () => {

  return (
    <>
      <Head>
        <title>Solana Token Balance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <section>
      <main> Solana Token Balance </main>
      <div className="content">
       <div className="token">
       <span> USDC </span>
      <img src="https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png?1547042389" alt="usd-coin" />
      <GetUsdcTokenBalance/>
       </div>
      </div>
      <div style={{display:"flex", alignItems:"center", justifyContent:"center",flexDirection:"column"}}>
         <h1> Wallet Connect  </h1>
       <WalletMultiButton />
     </div>
      

      </section>

   

    
    </>
  )
}

export default Home
